#!/usr/bin/perl

use warnings;
use strict;

use FindBin;
use lib $FindBin::Bin;

use EximQueue;

my $dir = EximQueue->DEFAULT_QUEUE_DIR;
use Getopt::Long;
GetOptions(
	"directory|d=s"	=> \$dir,
) or exit 2;

my $q = EximQueue->new($dir);

print "Enter program text:\n" if not @ARGV and -t STDIN;
my $text = join "", <>;

my $foo = eval "sub {
	my (\$p, \$peer) = \@_; \@_ = ();
	{
$text
	}
}";

die $@ if $@;

my $sub = sub {
	my $p = shift;
	my $peer = $p->get_sending_peer;
	eval { &$foo($p, $peer) };
	warn "$@" if $@;
};

$q->scan($sub);

# eof
