#!/usr/bin/perl

use warnings;
use strict;

use FindBin;
use lib $FindBin::Bin;

use EximQueue;

my $dir = EximQueue->DEFAULT_QUEUE_DIR;
use Getopt::Long;
GetOptions(
	"directory|d=s"	=> \$dir,
) or exit 2;

my $q = EximQueue->new($dir);

my $sub = sub {
	my $p = shift;
	() = $p->get_sending_peer;
	$p->{subject} = $p->get_header("Subject");
	$p->{contenttype} = $p->get_header("Content-Type");
	use Data::Dumper;
	print Data::Dumper->Dump([ $p ],[ 'p' ]);
	print "\n";
};

$q->scan($sub);

# eof
