#!/usr/bin/perl

use warnings;
use strict;

use FindBin;
use lib $FindBin::Bin;

use EximQueue;

my $dir = EximQueue->DEFAULT_QUEUE_DIR;
use Getopt::Long;
GetOptions(
	"directory|d=s"	=> \$dir,
) or exit 2;

my $q = EximQueue->new($dir);

my $todir = shift;
-d $todir or die $!;

print "Enter message IDs:\n" if not @ARGV and -t STDIN;

my %moveit;
while (<>)
{
	$moveit{$1} = 1 if /^(\w{6}-\w{6}-\w{2})\b/;
}

my $sub = sub {
	my $p = shift;
	my $id = $p->{message_id};
	return unless $moveit{$id};
	print "Moving $id\n";
	$p->move_to_queue($todir);
};

$q->scan($sub);

# eof
